Algoritmo "decisaosimples"
// Disciplina   : [ Lógica de Programação]
// Professor   : Joilson
// Descrição   : estrutura de decisao simples
// Autor(a)    : Kauan
// Data atual  : 05/09/2024
Var
// Seção de Declarações das variáveis 
Idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("digite sua idade")
leia (Idade)
se Idade > 18 entao
escreval ("voce e maior de idade")
fimse

Fimalgoritmo