Algoritmo "lacorepeticaopara"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : laco de repeticao "para"
// Autor(a)    : Kauan
// Data atual  : 17/09/2024
Var
   // Seção de Declarações das variáveis

   contadora:inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para contadora de 1 ate 10 passo 1 faca
      escreval("kauan")
   fimpara


Fimalgoritmo